version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
    - 2.18.3
    - 2.18.4
  - dependency-name: phing/phing
    versions:
    - 2.16.3
    - 2.16.4
  - dependency-name: pear/archive_tar
    versions:
    - 1.4.12
  - dependency-name: hashids/hashids
    versions:
    - 4.1.0
  - dependency-name: ramsey/uuid
    versions:
    - 4.1.1
